### ISSUE TITLE
Custom Path for Templates

### ISSUE THREAD

**Issue by gsihaj5** [ap/vim-templates#10]
I wonder, can i change path for the templates ?

i know i can put it on .config/nvim/templates, but if i want to push my whole nvim configuration file, i can't include the Plugged folder. by doing so i can store some of my own templates and use it across my device

**Comment by ap** [comment]
Well, it looks for them in a `templates` subdirectory – that part is not configurable.

But it looks for that subdirectory in every directory in your `&runtimepath` – so if you put the `templates` directory somewhere else and then add that location to your `&runtimepath`, it will find the templates in there.

Does that work for you?
