### ISSUE TITLE
Installation using vim-plug

### ISSUE THREAD

**Issue by zygimantus** [ap/vim-templates#9]
Can this plugin be installed using vim-plug? I was using this code:

```
call plug#begin('~/.vim/plugged')          

Plug 'ap/vim-templates'

call plug#end()
```

**Comment by ap** [comment]
I’ve never used vim-plug so I don’t know, but I would assume yes, since it‘s just a normal vim plugin and I can’t think of a reason why it wouldn’t work. I’ve never been told it doesn’t, either. What about that code you were using?

**Comment by zygimantus** [comment]
Actually it worked, I restarted my vim and was able to run :Template.
